# yamllint disable rule:line-length
---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build and Deploy the Docker Image
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            make build
            make push

# https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
  weekly:
    triggers:
      - schedule:
          # This project is rarely updated so run a weekly build.
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
